name: build

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.webapp.outputs.webapp-url }}
    steps:
      - uses: Azure/webapps-deploy@v3.0.6
        id: webapp
        with:
          app-name: gha-workshop
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/gutierrezfernando6/lesson9:latest'
          restart: true
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.6.0 
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - uses: docker/build-push-action@v6.18.0
        with:
          tags: ghcr.io/${{ github.repository }}
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
            
